### ISSUE TITLE
Is support for mobile platforms in the pipeline anytime soon?

### ISSUE THREAD

**Issue by ghost** [octoai/octo.ai#9]
It would be awesome to have some sort of SDK for integrating the Octo platform in the mobile apps.

**Comment by dipankar** [comment]
Actually we do have mobile SDKs

https://github.com/octoai/StarterKit-IOS-GCM
https://github.com/octoai/StarterKit-IOS-APNS
https://github.com/octoai/StarterKit-Android-Cordova
https://github.com/octoai/StarterKit-Android-Native
https://github.com/octoai/javascript-client

Why don't you write a nice PHP wrapper as well :)
